### ISSUE TITLE
Add twitter authentication

### ISSUE THREAD

**Issue by millross** [pac4j/vertx-pac4j-demo#17]
Add twitter authentication to vertx-pac4j-demo, comparable to that carried out by play-pac4j-demo

**Comment by plutext** [comment]
I tried adding twitter auth, but couldn't get it to work.

I was able to add linked in auth, and https://github.com/scribejava/scribejava/blob/master/src/test/java/org/scribe/examples/TwitterExample.java works properly for me.

The problem with twitter auth in vertx-pac4j seems to be that for that client, 
```
    ((IndirectClient) client).getRedirectAction(context, false).getLocation();
```
returns http://localhost:8080/callback?client_name=TwitterClient&needs_client_redirection=true

**Comment by millross** [comment]
Yes, I found that issue while I was adding twitter auth :) That's why all you currently see is facebook auth on the demo currently, fixing twitter auth before I go any further with the demo.

**Comment by millross** [comment]
It's not that the URL returned is wrong (based on the play-pac4j behaviour) it's that the handling of it is incorrect.

**Comment by leleuj** [comment]
More explanation on this: `getRedirectionAction.getLocation` returns the url to login at the identity provider. So in that case, we would expect to see some Twitter url.

Though, in some authentication mechanism (OAuth v1.0 here), the computation of this url is expensive because it requires to call the identity provider. So here is the concept of direct / indirect redirection. Direct redirection means that the url to the identity provider will be directly computed and provided. Indirect redirection means that you will be first redirected to the callback url to be then redirected to the identity provider.
Direct redirection should happen automatically for protected urls.

You can manage that with the second parameter in the `getRedirectAction` method: `false` here. Because we assume it's a computed link on a login page, and we don't want to call Twitter every time this page is displayed as we are not sure a Twitter login will be started.

**Comment by millross** [comment]
Issue pac4j/vertx-pac4j#53 is now resolved, I will be adding the twitter functionality soon.

**Comment by millross** [comment]
Twitter functionality added
