### ISSUE TITLE
Add multi profile "force Facebook login" endpoint

### ISSUE THREAD

**Issue by millross** [pac4j/vertx-pac4j-demo#39]
Add multi profile "force Facebook login" endpoint

Also check against latest play-pac4j-demo to ensure we cover all the behaviour featured in that demo. Once we do, and we're confident it all works, issue a vertx-pac4j release.

**Comment by millross** [comment]
This is currently under way. Also need to check CSRF stuff is working properly.

**Comment by millross** [comment]
Updated custom Facebook authorizer wording, modified profile display to support a list of authenticated profiles.

**Comment by millross** [comment]
CSRF stuff not covered as it's not in the j2e demo. Awaiting clarification on this from Jérôme - if we need to implement it I'll add a new issue.

**Comment by leleuj** [comment]
A CSRF example has been added in the Play demos because there was an issue with the web context implementation in Play to make CSRF work.
This is not really needed in the Vertx demo, nor in the J2E. CSRF mechanism is already covered by unit tests in the pac4j project.
I'll test the Vertx demo next week and cut the release if everything is ok.

**Comment by millross** [comment]
Awesome thanks - I updated the vertx-pac4j docs as well so you might want to read through those and flag up any problems. Also please let me know if you run into problems with the demo that suggest I've missed something. But hopefully we will have a release next week :) Have a great weekend.
